name: Portfolio Deployment

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AKIA6E52S2LMKH4Q3QYG }}
        aws-secret-access-key: ${{ secrets.Iym0SbjtEOmPgT7Q4ZSvCYyUTObGk5+WNJ7UfGxb}}
        aws-region: us-east-1

    - name: Deploy static site to S3 bucket
      run: aws s3 sync . s3://aditya-portfolio-web-project-01 --delete
